version: "3"
services:
  web:
    image: tomcat
    volumes:
      - ./web:/usr/local/tomcat/webapps
      - ./logs/web1:/usr/local/tomcat/logs
      - ./tmp:/home/test
    environment:
       TZ: Asia/Shanghai
       DUBBO_IP_TO_REGISTRY: ${hostIP} 
       node.name: ${hostIP}-web
    ports: # 端口转发 宿主:docker
      - "${web_port}:8080"
      - "${dubbo_port}:20887"      
    expose:
      - "8080"
      - "20887"
    extra_hosts:
      - "container_zookeeper:28.0.7.11" 
      - "container_nginx:28.0.7.11"       
      - "redis:28.0.7.11"
      - "sftp:28.0.4.14"
      - "mysql:28.0.4.13"      
    container_name: ${hostIP}-web
    networks:
      default:
         aliases:
          - ${hostIP}_web

  api:
    image: tomcat
    volumes:
      - ./api:/usr/local/tomcat/webapps
      - ./logs/api1:/usr/local/tomcat/logs
    environment:
       TZ: Asia/Shanghai
       node.name: ${hostIP}-api
    ports: # 端口转发 宿主:docker
      - "${api_port}:8080"       
    expose:
      - "8080"
    depends_on:
      - web
    extra_hosts:
      - "container_zookeeper:28.0.7.11" 
      - "container_nginx:28.0.7.11"       
      - "redis:28.0.7.11"
      - "sftp:28.0.4.14"
      - "mysql:28.0.4.13"   
    container_name: ${hostIP}-api
    networks:
      default:
         aliases:
          - ${hostIP}_api
          
networks: ##定义网络组
  default: 
   