version: "3"
services:
  nginx: # 服务的名称
    image: nginx
    volumes: # 文件夹映射
      - ./nginx/html:/usr/share/nginx/html # 宿主:docker:只读  ,www目录
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf # nginx配置文件
      - ./nginx/conf/conf.d:/etc/nginx/conf.d # nginx配置文件
      - ./logs/nginx:/var/log/nginx  #日志
    environment:
       TZ: Asia/Shanghai
    ports: # 端口转发 宿主:docker
      - "${nginx_port}:80"
    expose:
      - "80"
    extra_hosts:
      - "sftp:28.0.4.14" 
      - "container_web1:28.0.7.12"
      - "container_web2:28.0.7.13" 
    container_name: nginx-web
    networks:
      default:
         aliases:
          - nginx

networks: ##定义网络组
  default:
   